### ISSUE TITLE
Deserialization

### ISSUE THREAD

**Issue by timabdulla** [JSONAPI-Resources/jsonapi-resources#133]
Before I go to the trouble to craft a PR, would there be any interest from the maintainers in supporting custom operation types so that it would be possible to override the normally selected operation for a specific controller action on a controller-by-controller basis? This would allow us to support more complex deserialization requirements than is currently possible with the default set of operations.

**Comment by timabdulla** [comment]
Or maybe the better approach to more complex deserialization would be hooking into the replace_fields callback?

**Comment by barelyknown** [comment]
I believe that you can do what you'd like now (unless I'm not understanding). You can override a method for an individual controller to use whatever operation you'd like, and/or you could override the `create_operations_processor` method in the `ResourceController`. If you're thinking of something else, can you give a bit more detail?

**Comment by lgebhardt** [comment]
I'm concerned when you say on a "controller-by-controller basis". If we are going to go with custom operations (and I've assumed we would eventually add them) I think those should be controlled by the `Resource`. We can create default methods on the `Resource` to get each operation and modify the `Request` class to use those methods instead of assuming the operation type to create. That will allow custom operations, and they will be consistent no matter which controller creates the operation, which might be an issue when we implement a batch extension to the spec.

If you do want to customize the controller, I think it's really the `Request` object that's the better candidate since the `ResourceController` is fairly thin and most of the logic for the CRUD is in the `Request`. In `setup_request` we could check for a `Request` with a name matching the `Controller` prefix and if found use it instead of the base `Request` object.

Maybe a combination of both is most appropriate. I'm just throwing these ideas out there, but I'd like more discussion around intended use cases and impacts to existing code before we commit to anything.

**Comment by timabdulla** [comment]
Now that I've thought it about more, this behaviour should not exist at the controller level, and adding custom operations is probably overkill for my specific use case as well, though I can see the argument for  their usefulness.

Essentially my aim is to allow for more sophisticated deserialization for create and update requests. Right now, it is assumed that there is a perfect correspondence between the received JSON parameters and the model attributes when replacing fields. I would like the ability to intercept the received JSON and modify it to be congruent with the actual application-level attribute structure and then have the normal replacing of fields occur with my modified parameters.

For example, let's assume that I present to the user a `full_name` attribute in the resource, and expect the user to use that attribute when updating or creating resources, despite the fact that internally, I separate the `full_name` attribute into separate model fields. I would like to be able to modify the received parameters when creating or updating resources before having the field replacement performed. There is no easy way to do this currently, though it is possible with a bit of hackery. Ideally, the `replace_fields` callback could be sophisticated by having the caller also pass in the field values so that the callee can modify them if they want. Is there support for this extension?

**Comment by timabdulla** [comment]
My colleague @mmartinson has also suggested instead allowing for optional writer decorators, so that all attribute-setting done in update or create operations could be proxied to a decorator object which can then transparently handle any deserialization that might need to occur.

**Comment by barelyknown** [comment]
For your example, what about having a `full_name=` setter on the model?

**Comment by timabdulla** [comment]
That's fine in the very simple case I used as a motivating example, but for more complex deserialization, I wouldn't want to overburden the models with deserialization logic that doesn't belong in the domain layer.

**Comment by fotinakis** [comment]
Related: https://github.com/cerebris/jsonapi-resources/issues/129#issuecomment-87150515

**Comment by lgebhardt** [comment]
Instead of putting the `full_name=` method on the model, I'd say to put it on the `Resource`. I think that's the right level for that type of transform. You could also put a getter on the resource that really gets and combines the two fields on the model. That way the resource acts as a translation layer between the API and the model.
