### ISSUE TITLE
Hi, i get this error when i run rails server 

### ISSUE THREAD

**Issue by francelwebdev** [JSONAPI-Resources/jsonapi-resources#1351]
Hi,

I'm a beginer rails developer and i want to build an api with rails.
I get this error with this gem.

/home/francel/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant': uninitialized constant ActionController::ForceSSL (NameError)

Please how to solve this error.
Thanks

**Comment by marcelolx** [comment]
@francelwebdev This has already been fixed in this PR https://github.com/cerebris/jsonapi-resources/pull/1346, @lgebhardt is working on a new release. While this don't happens do you can use the master branch of this gem, look at your Gemfile where is this line `gem "jsonapi-resources"` and change it to `gem "jsonapi-resources", github: "cerebris/jsonapi-resources"` and then run `bundle install`, this will fix your issue until a new release is shipped.

**Comment by lgebhardt** [comment]
This should be fixed in the new v0.9.12 and v0.10.4 releases.
