### ISSUE TITLE
order of filters

### ISSUE THREAD

**Issue by ahmadabdelhalim** [JSONAPI-Resources/jsonapi-resources#1360]
I'm using ransack for search and I added a filter for searching 

```
filter :q, apply: ->(_records, value, _options) {
    Driver.search(value.first).result
  }
```

The problem is when I try to use filters on the resource, for example, when I do **_drivers?filter[supplierId]=4&filter[q]=name_**
It doesn't work correctly and I get all results without the first filter applied. It only works when I order the filters, for example, **_drivers?filter[q]=name&filter[supplierId]=4_** works correctly 

I don't understand what's causing this and why the order is important

**Comment by tommy-russoniello** [comment]
This is because you're not using the `records` parameter in your custom ransack filter. Filters need to build on the existing record set, otherwise they essentially reset everything (hence why it works only when the custom filter is applied first). This can also cause problems with anything else that builds up the query, such as sorting.

I haven't used ransack personally, but I believe just calling the `search` method on the `records` parameter will work.

**Comment by ahmadabdelhalim** [comment]
Thank you for clarifying.
