### ISSUE TITLE
What's the status of version 0.11.0?? IS THIS PROJECT DEAD?

### ISSUE THREAD

**Issue by tilo** [JSONAPI-Resources/jsonapi-resources#1404]
IS THIS PROJECT DEAD? 

Version [0.11.0.beta was 3 years ago](https://github.com/cerebris/jsonapi-resources/blame/856f139a95abb0a5efc2949d1706aa1f8f8048b0/lib/jsonapi/resources/version.rb#L3)

**Comment by tilo** [comment]
didn't realize the dev work for 0.10.x was on a branch

**Comment by lougreenwood** [comment]
@lgebhardt I'm a FE dev who's curious about promoting this within our org to get more consistency across our JSON:API endpoints. But I'm struggling to understand the state of the project?

Seems there are a bunch of open PRs, a v0.11 branch which is 2 years old and PRs being merged into master.

What's the state of the project, because at the moment it looks dead and not a good idea to adopt this. Are you looking for new maintainers, is there a roadmap for v0.11?

✌️
