### ISSUE TITLE
Camelized keys in json

### ISSUE THREAD

**Issue by opsb** [JSONAPI-Resources/jsonapi-resources#17]
Very pleased to see JR surface. I'm planning on using jsonapi-resources with ember-orbit so I'm putting together an example app at the moment. I see that the json keys are currently underscored but shouldn't they be converted to camelized keys?

**Comment by opsb** [comment]
Workaround for now

### application.rb

```
config.after_initialize do
    require Rails.root.join("lib", "jsonapi", "resource_serializer_ext.rb")
end
```

### lib/jsonapi/resource_serializer_ext.rb

```
module JSONAPI
    class ResourceSerializer
        alias_method :original_serialize, :serialize

        def serialize(source, include = [], fields = {}, context = nil)
            primary_hash = original_serialize(source, include, fields, context)
            convert_hash_keys(primary_hash){ |key| format_key(key) }
        end

        def format_key(key)
            key.to_s.camelize(:lower)
        end

        def convert_hash_keys(value, &block)
            case value
            when Array
                value.map { |v| convert_hash_keys(v, &block) }
            when Hash
                Hash[value.map{ |k, v| [(yield k), convert_hash_keys(v, &block)] }]
            else
                value
            end
        end     
    end
end
```

**Comment by opsb** [comment]
Same problem with the request coming in, need to convert camelcased to underscored. I'm not sure what your intentions are, I can't find any guidance in the jsonapi spec but seeing as we're dealing with json I think that camelcased is the most appropriate format (the jsonapi adapter for ember-orbit certainly assumes camelcase).

**Comment by lgebhardt** [comment]
@opsb, as far as I know the JSONAPI spec is agnostic on camelcase vs underscores. Since JR is a Rails extension I defaulted to using the Rails conventions. This makes sense if you are trying to add an API to an existing Rails application. However if you are creating an API only application to be consumed by JavaScript I can see wanting to support camelcase by default. We've been handling the translation on the client side, but I think it might be best to just avoid the whole mess and camecase things.

I'll take a look at an option to have JR support both modes. I think it should be fairly straight forward for reading data in and out. For consistency I assume you would want the routes to also use camelCase? I haven't played around with the `camelize` method, but it looks like it uses inflections so it should be easy to update the rules. That should make it clean to rely on the method.

Thanks for bringing this up.

**Comment by opsb** [comment]
@lgebhardt I suspect that camalised will become the default for JSONAPI libraries but there's no harm in having an option. I'd actually expect the routes to be underscored, they're nothing to do with JSON and I think it's a strong convention on the server side (obviously within the rails world but I suspect elsewhere as well). I think all cases can be covered fairly easily with something like

```
JSONAPI.config do |config|
    config.jsonKeyFormat = :camelised # default or :underscored
    config.routeFormat = :underscored # default or :camelised
end
```

but to be honest I think most people will want underscored routes so that second config option probably isn't worth the effort unless someone is asking for it.

**Comment by dgeb** [comment]
I agree with @opsb that we should separate out the `jsonKeyFormat` from the `routeFormat`. I think we should also support `dasherized` as an option for both.

I'll also enhance the JSONAPISerializer in ember-orbit to more easily support these options.

**Comment by lgebhardt** [comment]
Ok, I'll work something up.

**Comment by dgeb** [comment]
@lgebhardt thanks :+1:

**Comment by lgebhardt** [comment]
Closing. Please reopen if this doesn't work for you.
