### ISSUE TITLE
Update relationship has one should send payload with pluralised key

### ISSUE THREAD

**Issue by opsb** [JSONAPI-Resources/jsonapi-resources#20]
The current test seems to be out of line with the jsonapi spec,

```
def test_update_relationship_has_one
  ruby = Section.find_by(name: 'ruby')

  post :create_association, {post_id: 3, association: 'section',
                 section: ruby.id }

  assert_response :success
  assert_equal 1, json_response['posts'].size
  assert_equal 3, json_response['posts'][0]['links']['author']
  assert_equal  ruby.id, json_response['posts'][0]['links']['section']
  assert_equal 'AAAA', json_response['posts'][0]['body']
end
```

from the spec

> A to-one relationship MAY be added by sending a POST request with an individual primary resource to the URL of the relationship. For example:
> 
> POST /articles/1/links/author
> Content-Type: application/vnd.api+json
> Accept: application/vnd.api+json
> 
> {
>   "people": "12"
> }

notice that the key is pluralised in the example from the spec but it's singular in the test case.

**Comment by lgebhardt** [comment]
I found implementing this part of the spec a bit confusing. JR is returning the full parent resource based on this in the JSONAPI:

> If a server accepts an update but also changes the resource(s) in other ways than those specified by the request (for example, updating the updatedAt attribute or a computed sha), it MUST return a 200 OK response as well as a representation of the updated resource(s) as if a GET request was made to the request URL.

I return the full resource since the updated_at field is being updated (in most rails implementations - no check is done). 

The plural resource you are referencing is a relationship resource, and would make more sense as the response to a update on the relationship resource. But in this case it seems that nothing else on the relationship resource could change, so really the response should be a 204 No Content.

There's one issue about this on JSONAPI and I just talked with @dgeb. He's considering some changes to this section. I'd like to wait before coding anything related to this until we see the changes.

**Comment by opsb** [comment]
@lgebhardt it's the request that I was looking at, according to the spec(as far as I've understood it anyway) the request sent in that test should have a pluralised section i.e.

```
post :create_association, {post_id: 3, association: 'section',
             sections: ruby.id }
```

**Comment by lgebhardt** [comment]
Ok, I see that now. Thanks for catching that. I'll get that fixed ASAP.
