### ISSUE TITLE
ResourceSerializer#self_href doesn't generate correct links for mounted engines

### ISSUE THREAD

**Issue by achan** [JSONAPI-Resources/jsonapi-resources#268]
When mounting an engine that uses `jsonapi-resources` to a custom folder like so:

``` ruby
Rails.application.routes.draw do
  mount Basechurch::Engine => "/api"
end
```

All my links are not taking into account the custom folder when generated.

When hitting the following endpoint:

`GET http://example.com/api/v1/bulletins/2`

My response looks like so:

``` json
{
    "data": {
        "id": "2",
        "type": "bulletins",
        "links": {
            "self": "http://example.com/basechurch/v1/bulletins/2"
        }
        ...
    }
}
```

I'm pretty sure the issue is that the `ResourceSerializer` doesn't take into account mountable paths when formatting module names in resource class names: https://github.com/cerebris/jsonapi-resources/blob/4e46ed00606440f7136b041a6ead4c8353bc4a4b/lib/jsonapi/resource_serializer.rb#L215. Is this out of scope for the `ResourceSerializer`? Should I create a `MountedEngineResourceSerializer` for myself?

**Comment by lgebhardt** [comment]
@achan I'll see if I can get this figured out. In the meantime creating your own serializer might be a good temporary fix.

**Comment by thewatts** [comment]
@achan -> did you also have to specify the `model_name` in the `BulletinResource`?

ex: `model_name "Basechurch::Bulletin"`

**Comment by achan** [comment]
Yes I did: [source](https://github.com/openmcac/basechurch/blob/master/app/resources/basechurch/v1/bulletin_resource.rb#L14)

And if it's any use to you, [here's the resource serializer](https://github.com/openmcac/basechurch/blob/master/app/lib/basechurch/resource_serializer.rb) I hacked up to hardcode my custom engine mount path.

**Comment by thewatts** [comment]
@achan && @lgebhardt 

The tricky thing here is finding out, within the scope of the serializer, where the engine (if it is in fact an engine) is being mounted within the parent app. You can find out by calling, say:

``` ruby
# `source` is available within the scope of the serializer,
#    it is the individual item in which we're getting the `self_href` for.
#    let's just say that the source's id is 5.
#    (Notice that the mount point is included within the returned url)
Basechurch::Engine.routes.url_helpers.v1_bulletin_path(source.id)
# => "/api/v1/bulletins/5"
```

Within the scope of the serializer, there is the available `@primary_class_name` variable, that in the above case would be `:basechurch`.

The source in this case is an instance of `Basechurch::V1::BulletinResource`. With that knowledge, you can take the class name, find out the scope, and use it to build the pathname you'd need:

``` ruby
scopes = source.class.name.split("::")[1...-1]
# => "V1"
base_path_name = scopes.map { |scope| scope.downcase }.join("_")
# => "v1"
end_path_name = source.class._type.to_s.singularize
# => "bulletin"
path_name = "#{ base_path_name }_#{ end_path_name }_path"
# => "v1_bulletin_path"

Basechurch::Engine.routes.url_helpers.send(path_name, source.id)
# => "/api/v1/bulletin_path/5"
```

This makes some assumptions (ie: that the route name would line up with the namespacing, such as `v1_bulletin_path` instead of `my_awesome_bulletin_path`) - and there would definitely have to be some error checking.

@lgebhardt this is a bit magical for sure - and I wasn't confident that it'd be something you'd want in the gem. If you do - I'd be game to submit a PR, just let me know :)

**Comment by lgebhardt** [comment]
@thewatts Getting support for engines would be nice, and a PR would be appreciated. Ideally I'd like to get to a solution that works with a minimum of configuration for using engines or not. I haven't really tried the code above, so I'm not sure how close it comes to that ideal.

**Comment by thewatts** [comment]
@lgebhardt && @achan --> opened a WIP Pull Request #298 (needs tests and a refactor)

@achan would love to know if this works on your end (functionality is there - at least, when I tested locally with my own engine).

**Comment by achan** [comment]
@thewatts It doesn't seem to work for me. My Gemfile.lock indicates that I've got your branch installed, but `/api/v1/bulletins/20` still looks like this:

``` json
{
    "data": {
        "id": "20",
        "type": "bulletins",
        "links": {
            "self": "http://basechurch.dev/basechurch/v1/bulletins/20"
        },
    ...
}
```

Sorry I can't provide any more information at the moment :disappointed: but I'll see if I can help out when I can free up some time.
