### ISSUE TITLE
Complex / preset filter on the server

### ISSUE THREAD

**Issue by esasse** [JSONAPI-Resources/jsonapi-resources#278]
I have a complex filter for a specific resource that all clients of my API are going to need.

Is it possible to create a preset filter on the server so that the client wouldn't need to build it in the request url?

Something like: `http://example.com/contacts?filter[my_preset_filter]`

I saw the `apply_filter` options in the readme, but l understand they should be used to customize filters to specific fields. In my case, the complex filter I have is going to use more than one field, so the `apply_filter` customization doesn't look like the solution.

**Comment by slaskis** [comment]
As far as I understand the specification does not define in any detail _how_ the filters will work. So you're free to implement it as you like.

JR on the other hand does present some defaults where it filters by a field. But I think as long as you return a set of records (or a Relation) in `apply_filter` it doesn't care if it's one or more fields.

Something like `?filter[preset]=complex` would be parsed into _filter_: `preset` and _value_: `["complex"]` (because it split's the value on commas). Then you can interpret `["complex"]` however you like, such as `records.where(x: 1, y:2)` if you like.

**Comment by esasse** [comment]
Perfect! I can even use the way I wanted `?filter[my_preset_filter]` and I'll get `my_preset_filter` in `apply_filter` method.

**Comment by esasse** [comment]
Thanks @slaskis!

**Comment by slaskis** [comment]
Glad I could help @esasse!
