### ISSUE TITLE
Related records route mismatches parameter when primary key of resource is not id.

### ISSUE THREAD

**Issue by jonkoops** [JSONAPI-Resources/jsonapi-resources#296]
I made a simple setup of a blog application to illustrate my issue. The app has a Post resource with the primary key set to `slug`. A post can have many comments so a Comment resource is also included.

**app/models/post.rb**

``` ruby
class Post < ActiveRecord::Base
  self.primary_key = 'slug'

  has_many :comments
end
```

**app/resources/post_resource.rb**

``` ruby
class PostResource < JSONAPI::Resource
  primary_key :slug
  attributes :slug, :title, :body
  has_many :comments

  def self.verify_key(key, context = nil)
    key && String(key)
  end
end
```

**app/models/comment.rb**

``` ruby
class Comment < ActiveRecord::Base
  belongs_to :post
end
```

**app/resources/comment_resource.rb**

``` ruby
class CommentResource < JSONAPI::Resource
  attributes :author, :body
  has_one :post
end
```

With this setup I can get a list of posts without any issues by visiting `/posts/` and the link to the comments associated with this post is showing up correctly as well. However when I try to visit the link to list the comments associated with a specific post (i.e. `/posts/my-cool-post/comments`) I get the following response:

``` json
{
  "errors": [{
    "title": "Missing Parameter",
    "detail": "The required parameter, post_slug, is missing.",
    "id": null,
    "href": null,
    "code": 106,
    "path": null,
    "links": null,
    "status": "bad_request"
  }]
}
```

A `post_slug` parameter is expected to be passed but it is not. Upon further inspection I found that the route is defining a parameter named `post_id` instead. My guess it that either I have missed something very obvious or that the function is incorrectly expecting a parameter named `post_slug` while it should be using the `post_id` parameter.

**Comment by Yoshyn** [comment]
+1

**Comment by iamvery** [comment]
I dug into this a little more and found out the source. The problem is the parameter generated by the route is `[resource name]_id`. You can see this with `bin/rake routes`. But the resource controller via strong parameters checks that a parameter by the name of the resource's parent key. If you follow that to [it's implementation](https://github.com/cerebris/jsonapi-resources/blob/8e4702cde4718a7d183a8d78b23470243744fa03/lib/jsonapi/resource.rb#L584), you'll see that the definition of "parent key" is `[resource type]_[primary key]` which doesn't match the param that is defined by default in the routes.

Sooo, one option would be to use the `:param` option to the `resources` route method to override the parameter name. Unfortunately, the `jsonapi_resources` helper [explicitly overrides the `:param` option to be `:id`](https://github.com/cerebris/jsonapi-resources/blob/8e4702cde4718a7d183a8d78b23470243744fa03/lib/jsonapi/routing_ext.rb#L67). I confirmed that changing that line to `options[:param] ||= :id` would allow specifying a custom param, but I'm not sure how the maintainers would want to approach the problem.

**Comment by jonkoops** [comment]
@iamvery I think it would make sense to keep the name given by the route since the JSON API specification requires a resource to have a unique identifier.

**Comment by jonkoops** [comment]
@lgebhardt Could you confirm wether this behaviour is a bug or not, or where we could override these defaults?

**Comment by lgebhardt** [comment]
@jonkoops I'm not sure at this point. I'll look into it.

**Comment by jonkoops** [comment]
@lgebhardt I noticed the issue @iamvery mentioned was resolved. You might have fixed the issue in [this pull request](https://github.com/cerebris/jsonapi-resources/pull/293). Not quite sure though.

**Comment by lgebhardt** [comment]
@jonkoops Ok. If it's been resolved could you please close this issue. If not I'll try to look soon.

**Comment by jonkoops** [comment]
@lgebhardt I checked using the v0.5.0 release, but the problem is still present.

**Comment by lgebhardt** [comment]
Thanks for checking. I'll look at it soon.

**Comment by jonkoops** [comment]
Release v5.0.1 fixes this issue, thanks for your work @lgebhardt!
