### ISSUE TITLE
Always use singular version of `type`

### ISSUE THREAD

**Issue by brandonparsons** [JSONAPI-Resources/jsonapi-resources#306]
Hi there,

How can I configure `JR` to always use the singular version of `type` rather than plural?

I'm trying to use `JR` with `ember-data 1.13.5`, and the new `store.push` API which accepts a JSON-API formatted document.  When I push the response from `JR`, I get `no model found for 'posts'` because it is returning the plural version for type, whereas my ember app has a model for `post`.

**Comment by bmac** [comment]
Hi @brandonparsons. Ember Data should work well with jsonapi-resources. While its true Ember Data's `store.push` method accepts a JSON API document that has singularized types and camelCased attributes names, Ember Data ships with a `JSONAPISerializer` that will automatically singularize the types and camelCase the attribute names returned by jsonapi-resources. If you use `store.pushPayload` instead of `push` Ember Data's store will run your payload through the serializer to make these changes before pushing the data into the store.

**Comment by brandonparsons** [comment]
Thanks for the quick reply @bmac . I tried `pushPayload`, but I thought it would be convenient to use `push` as it would return the resource.  A combination of `pushPayload` and `peekResource` would be the way to go then?

**Comment by brandonparsons** [comment]
@bmac Takes an extra line of code (doesn't matter!) and works:

``` javascript
      .......then( response => {
        var pushed = this.store.pushPayload(response);
        return this.store.peekRecord('post', response.data.id);
      })
```

Although this doesn't solve my original question, it solves the problem I was having. I'll close the issue.
