### ISSUE TITLE
Am I supposed to disable strong params? Or have it enabled?

### ISSUE THREAD

**Issue by krzkrzkrz** [JSONAPI-Resources/jsonapi-resources#317]
I have a request being sent to http://localhost:4099/api/v1/items/199 (`PATCH`).

It seems JR can't find `data` when it is clearly in the payload.

I get:

```
{"errors":[{"title":"Missing Parameter","detail":"The required parameter, data, is missing.","id":null,"href":null,"code":106,"path":null,"links":null,"status":"bad_request"}]}
```

But the payload has:

```
{"data":{"id":"199","attributes":{"count":3,"status":null},"relationships":{"user":{"data":{"type":"users","id":"128"}},"product":{"data":{"type":"products","id":"1619"}},"checkout":{"data":null}},"type":"items"}}
```

**Comment by lgebhardt** [comment]
JR does use strong parameters. I haven't tried disabling it.

**Comment by krzkrzkrz** [comment]
Any reason why it can't find `data` then? Is the expected payload correct?

**Comment by lgebhardt** [comment]
The payload looks correct. How are you calling the method? Have you looked at the params in a debugger? See what's coming into the Request.setup_action method. Hopefully it will be obvious when you look in there.

**Comment by krzkrzkrz** [comment]
How do you mean? This is what I have. It also doesnt seem like the actions are being called from the controller first. Otherwise, `raise` would have executed....

```
class Api::V1::ItemsController < JSONAPI::ResourceController

  def setup_action
    raise 'a'
    #puts params
    #super
  end

  def show
    raise 'b'
    #super
  end

  def index
    raise 'a'
    #super
  end

  def update
    raise 'asdf'
  end
end
```

**Comment by jmaziarz** [comment]
I'm having the same issue. Did you find the cause?

**Comment by jmaziarz** [comment]
I have a test that reproduces this in my fork of the Peeps sample app: https://github.com/jmaziarz/peeps/commit/a0ea30d7570c85f0531afc7c5b173df9ee79be83

**Comment by koriroys** [comment]
@jmaziarz you need to use hyphens and not underscores in your payload.

so 'name_first' and 'name_last' should become 'name-first' and 'name-last'

Then you should have passing tests.

**Comment by koriroys** [comment]
@krzkrzkrz my guess is it doesn't like `"checkout":{"data":null}}`. Can you verify that your checkout relationship doesn't require `data`?

**Comment by evolve2k** [comment]
After getting some support from @lgebhardt it seems the likely fix here is that you are explicitly declaring **application/vnd.api+json** in any of a number of configuration places within your rails app (probably in a few initializers and prossibly as a legacy from coming across from AMS). 

The fix is this:
*\* Remove all references to application/vnd.api+json that may be explicitly declared anywhere in your app.**

More details are in related issue #850.

Also @lgebhardt looked over @jmaziarz code example and stated "jmaziarz/peeps@a0ea30d has a bug in the test which is why it's failing at times. The underscored parameters should be hyphenated (by default) and the config option that's being tested is simply letting them slide by with a warning."  

So it seems in it's current state this is not a separate open issue.
Everyone try the suggested approach and reopen/make new issue if something different arises.

Admins: Recommend close

**Comment by evolve2k** [comment]
To answer the explicit question of @krzkrzkrz "Am I supposed to disable strong params? Or have it enabled?". You don't need to touch it, a strong params issue will tell you so in your Rails Logs, which is not the error that we are getting here. This is a different issue as explained above. So no strong params is not the problem.

**Comment by lgebhardt** [comment]
It's possible that the issue encountered by @krzkrzkrz is related to overriding the mime type handler that JR defines. Plus the answer to the posed question is: Yes, you need Strong Parameters for JR for function correctly. So I've closed this issue. Please open a new issue (and reference this one if you feel it's still relevant) so it gets more visibility.
