### ISSUE TITLE
Incorrect total count when using include param

### ISSUE THREAD

**Issue by apraditya** [JSONAPI-Resources/jsonapi-resources#381]
Requesting `/api/v2/posts?include=categories` I get `"total": 1` in the meta object, but without `include` param, I get 88. Everything else is the same. Happens on all the versions I tried (0.4.4, 0.5.x and master)

**Comment by lgebhardt** [comment]
Other than the meta `total` is the rest of the response correct?

**Comment by apraditya** [comment]
Yes, the rest is correct. Interestingly, the response is also correct on _synthetic_ relation like `/api/v2/users/5/top-posts?include=categories`. Synthetic as in like this:

```
class UserResource < JSONAPI::Resource
  has_many :top_posts, class_name: 'Post'
end

class User < ActiveRecord::Base
  def top_posts
    posts
      .order(comments_count: :desc,
             total_read: :desc,
             bookmarks_count: :desc)
  end
end
```

May be I need to check on my code. But I have no idea which part.

**Comment by lgebhardt** [comment]
That's interesting. The two cases you show are going through different paths to get the counts. I'm not able to reproduce the issue, but I'm thinking this architecture is in need of some rework.

Which database are you using? If you look at the logs can you see anything odd with the queries that are being run?

I'm assuming you have set the `top_level_meta_record_count_key` to `total` and this issue is thus originating in the standard `record_count` code. Can you confirm?

**Comment by apraditya** [comment]
You're right, I've set it to `total`. Changing to the standard `record_count` does not solve it though.

**Comment by lgebhardt** [comment]
Thanks. I didn't think that was the issue, but was just making sure I was looking at the right section of code for the bug.

**Comment by apraditya** [comment]
Sorry, my bad I put this class method

```
def find_count(filters, options = {})
  filter_records(filters, options).count(1)
end
```

as a work around to support a custom filter I made. It was using version 0.4.4 back then. Once I remove it specs are green, everything works.

**Comment by lgebhardt** [comment]
Thanks for letting us know.
