### ISSUE TITLE
Mechanism for hooking exception logging services (Honeybadger, etc..)

### ISSUE THREAD

**Issue by bvandenbos** [JSONAPI-Resources/jsonapi-resources#390]
JR does a nice job of returning properly formatted errors in the case of an exception, however since it's handling the errors, standard exception logging doesn't work out of the box (unless i'm missing something).

A couple additions come to mind:

1) A Operations callback for "after_exception" which allows one to define behavior when an exception occurs for a given resource.  An example would be logging instrumentation or logging to a statsd service.
2) Global config to exception logging/handling where you can register handlers/adapters.  The intended use would be for exception logging to something like Honeybadger, but could have other uses as well. 

I poked around to see if there was already something like this in place but came up empty.  Please correct me if I missed it.  

I do realize I can add my exceptions to the whitelist and let them "bubble up" to rails, but that's not the desired behavior.  I _want_ JR to handle them, I just want to hear about it.

Doing a quick code dive, it seems like updated `process_operation` to additionally hook callbacks where it's currently writing to the rails log would be a good starting place.

**Comment by lgebhardt** [comment]
Good ideas. You are correct that the system doesn't currently have something like this. And I think `process_operation` would be the correct place to trigger the callback.

**Comment by mmartinson** [comment]
I just saw this after submitting #415 today. @bvandenbos maybe you'd have a look to see how it handles your use case. 
After some consideration I was leaned towards handling this in the controller rather than the resource, but that's not necessarily the right answer. I wanted to add airbrake monitoring to all exceptions as well as some more specific logging to the rails logger and this seemed less obtrusive than adding it to the resource classes. My thought was that since all handle exceptions are passed back to the controller level to be rendered, as well as being where they are often caught in a conventional rails app, it made sense to stick with that pattern.

**Comment by bvandenbos** [comment]
At first blush, this looks perfect.  +1 on implementing at the controller level.  That's where I first expected to find something like this.  Thanks for doing this.  Closing.
