### ISSUE TITLE
How to add a custom link

### ISSUE THREAD

**Issue by ceritium** [JSONAPI-Resources/jsonapi-resources#464]
Hi,

I have the resource `Specification` and I want add a link to the raw file like:

``` json
{
  "data": [
  {
    "id": "26",
    "type": "specifications",
    "links": {
      "self": "http://localhost:3000/api/specifications/26",
      "raw": "http://localhost:3000/api/specifications/26/raw"
    }
},
```

How I could do it?

Thanks

**Comment by lgebhardt** [comment]
There isn't yet an official way to add additional links. Eventually I'd like to be able to add custom links to the resource and the relationships, but as of now we haven't started work on that.

I'm not sure the best way to accomplish this. Probably the simplest way would be to patch the `ResourceSerializer.relationship_links` and test for the source being equal to the specifications class and if so adding the additional link. It's ugly, but should work until we implement a better way.

If you, or anyone else, want to tackle adding this as a PR that would be even better. Eventually I'd like to have a `link` method on the resource to add a new link and provide a lambda to generate the link.

**Comment by ceritium** [comment]
Thank you very much

I'm not sure when I could try the patch, if works I will reply about that.

For my could be closed this issue :D

**Comment by akharris** [comment]
@ceritium +1 I had the same need for links that looked like the following

![screenshot 2015-09-30 12 48 27](https://cloud.githubusercontent.com/assets/5504772/10201329/71c18ca0-6779-11e5-9b86-fc26fd61a81b.png)

@lgebhardt I had the same need and have a [branch](https://github.com/cerebris/jsonapi-resources/compare/master...AKHarris:feature/custom-links-defined-per-resource) that implements a `custom_link` method that's defined on the Resource class. For example if you wanted to generate @ceritium's example you would define the SpecificationResource class as follows.

``` ruby
class SpecificationResource
  attributes :title, :description #etc

  custom_link :raw, :self
end
```

where the first argument `raw` is the name of the key and `self` is the 'kind' of url you want to generate, which in this case is an extension of the self url. While not yet implemented I, I wanted to leave open the possibility of defining custom links that hang off of the various relationship urls by passing in `:relationship` instead of `:self`.

if you wanted a longer path extended from the self link you could do that as follows. You could also add a custom extension

``` ruby
class SpecificationResource
  attributes :title, :description #etc

  custom_link :raw, :self, path: "super/duper/custom/path", extension: :xml
end
```

which would generate the following

```
{
  "data": [
  {
    "id": "26",
    "type": "specifications",
    "links": {
      "self": "http://localhost:3000/api/specifications/26",
      "raw": "http://localhost:3000/api/specifications/26/super/duper/custom/path.xml"
    }
},
```

While I did write tests I'm not too happy with the implementation and would love some feedback. If you're interested I can PR the branch I linked to above as a discussion piece.

**Comment by ceritium** [comment]
Awesome @AKHarris I could try later and maybe give you some feedback.

**Comment by ceritium** [comment]
@AKHarris I tested and works fine.

I think that you could PR the branch. The option `path` is interesting. But how to write something like:

``` json
{
"self": "http://example.com/api/specifications/23",
"other": "http://example.com/other-url",
}
```

Maybe you could provide two options:
- path, you must define the complete path.
- url, you can define any url even external resources.

**Comment by akharris** [comment]
@ceritium sorry for my delay. I will PR the branch today or tomorrow. Also, I like the idea of being able to add resources that are completely external :+1: 

I also had a use case where I wanted to add a custom link only if a model met a certain condition. In that case I added an option called `if` for a lambda. So, here's an extremely contrived example...

``` ruby
class Order < JSONAPI::Resource
  attributes :id, :customer_id, :price

  custom_link :receipt, :self, if: ->(instance) { instance.processed? }
  # builds a `<root-domain>/orders/:id/receipt` only if the order is processed
end
```
