### ISSUE TITLE
Using existing values to determine which fields are updatable

### ISSUE THREAD

**Issue by digitalcora** [JSONAPI-Resources/jsonapi-resources#586]
As a newcomer to this library I may be missing something obvious, but I have what seems like a simple requirement: An `Issue` can only be reassigned (which involves updating its `assigned_to` field) by the user it is currently assigned to. It looks like `self.updatable_fields` on the resource class would be the appropriate place to do this, except the `context` it receives is just the current user, which is not enough information to make the decision. `@model` is of course not available at the class level (well, strangely it is, but it points to the model _class_ which I guess makes sense). What am I not seeing?

**Comment by lgebhardt** [comment]
The `updatable_fields` method works at the resource class level, not at the instance. The operation processor callbacks can let you check values before allowing the operation to proceed. This isn't as easy as I'd like, so I'm hoping to do a refactor soon.

Sometimes I would like to do this type of check on the model instance as a validation or enforce the rules at the database level with scopes, but the rails way keeps the context away from the model and validations. To that end you could look at the [RequestStore gem](https://github.com/steveklabnik/request_store) to allow the context into the model instance. Not the rails way, but...

**Comment by digitalcora** [comment]
Thanks @lgebhardt. I was wondering about the rationale for making creatable/updatable fields be at the class level, especially since `fetchable_fields` is at the instance level.

Since this seemed like an authorization concern and we were already using Pundit for authorization elsewhere, I did end up creating a custom operations processor that uses a `permitted_attributes` method on the policy class, which is a Pundit convention. It looks something like this:

``` ruby
class AuthorizingOperationsProcessor < ActiveRecordOperationsProcessor
  before_replace_fields_operation :authorize_replace_fields

  def authorize_replace_fields
    policy = Pundit.policy!(@request.context.fetch(:current_user), existing_record)
    changing_attributes = @operation.data[:attributes].keys.to_set
    permitted_attributes = policy.permitted_attributes.to_set

    unless policy.update? && changing_attributes.subset?(permitted_attributes)
      raise Pundit::NotAuthorizedError
    end
  end

  def existing_record
    @operation.resource_klass.find_by_key(@operation.resource_id, @operation.options).model
  end
end
```

As you can see this is pretty ugly, and there is more code besides this to handle authorizing the reading, creating, and deleting of resources. I had to do a lot of code spelunking to figure out what instance variables were accessible and where the data I needed was located. And even after all that work, this approach ends up double-fetching each record from the database, because the internals of the operation fetch and save the record in a single step with no opportunity to intervene.

I see very recently there was a comment in #16 where someone started up a gem that attempts to do the same thing, so I will probably go look at their code now and track that issue for further updates.

**Comment by lgebhardt** [comment]
@grantovich Thanks for sharing your method. That double fetching is certainly no ideal. I'll give some thought as to how to get the library to handle this better.

**Comment by krasnoukhov** [comment]
I have a quite similar use case with `permitted_attributes`, so count me interested in a refactor.

**Comment by valscion** [comment]
Hi @grantovich and @krasnoukhov! Me and @lime are the authors of the referenced gem, [`jsonapi-authorization`](https://github.com/venuu/jsonapi-authorization), and we'd be happy to discuss this use case further on our repository.

Authorizing modification of just a subset of attributes seems to be a valid use case, and Pundit in fact even has that `permitted_attributes` functionality built in. Currently we're only just [authorizing the entire replace operation](https://github.com/venuu/jsonapi-authorization/blob/v0.5.0/lib/jsonapi/authorization/default_pundit_authorizer.rb#L94), but having the fields passed in to the authorizer's `replace_fields` method from the [`AuthorizingOperationsProcessor#authorize_replace_fields`](https://github.com/venuu/jsonapi-authorization/blob/v0.5.0/lib/jsonapi/authorization/default_pundit_authorizer.rb#L94) could be a good idea.

If you are in need of such a functionality, we're open for discussion and would be happy to discuss this even further with a PR :smile:. The default authorizer class could even be changed to use the `permitted_attributes` from Pundit policy, so that `replace_fields` operations (and possibly others, like `create_resource`) would use it.

**Comment by digitalcora** [comment]
@valscion Thanks for starting up that gem, it looks like a much better-generalized version of the custom operations processor we came up with :smiley: If I have some open-source time I may look at adding the `permitted_attributes` functionality, although for this project we will likely continue using the code we have until we have a reason to change it.

I'll close this particular issue for now, since we have something that works for our use case, the `jsonapi-authorization` gem can serve as a place for further development of this general idea, and #16 is there for discussing how `jsonapi-resources` can make authorization easier.
