### ISSUE TITLE
Unable to use hyphenated relationship names

### ISSUE THREAD

**Issue by thewalkingtoast** [JSONAPI-Resources/jsonapi-resources#605]
Hello!

I have a resource setup like so:

``` ruby
class UserInvitationResource < BaseResource
  attributes :invitation_token, :state, :expired, :inviter_id
  has_one :'lighthouse-profile', class_name: "LighthouseProfile", foreign_key: "profile_id"

  filter :invitation_token
end
```

When sending this POST payload to create a `UserInvitiation`, I get the right relationship links but no corresponding Lighthouse Profile resource is actually associated (`profile_id` remains `nil`):

``` json
{
  "data": {
    "attributes": {
      "inviter-id": 1
    },
    "relationships": {
      "lighthouse-profile": {
        "data": { "type": "lighthouse-profiles", "id": "1" }
      }
    },
    "type": "user-invitations"
  }
}
```

However, if I rename the `has_one` to just `profile` it works:

`has_one :profile, class_name: "LighthouseProfile", foreign_key: "profile_id"`

I've also tried `:lighthouse_profile` and get `TypeMismatch` error because the JSON uses hyphenated keys vs. underscore.

It appears as though I'm unable to have an association with hyphens in the name.

**Comment by lgebhardt** [comment]
@thewalkingtoast Sorry for the late reply, and I'm hoping you have found the answer by now. 

JR uses [Formatters](https://github.com/cerebris/jsonapi-resources#formatting) to convert rails names (underscored) into JSON API keys. The default is for hyphenated since that's the JSON convention. However you can convert to any other formatting system you want with custom formatters, of which  `hyphenated-key`, `dasherized_key`, and  `camelized_key` are included in JR. See `json_key_format` in the section on [Configuration](https://github.com/cerebris/jsonapi-resources#configuration).

Internal to resources your relationships should use the ruby/rails standard of underscores.

``` ruby
class UserInvitationResource < BaseResource
  attributes :invitation_token, :state, :expired, :inviter_id
  has_one :lighthouse_profile, foreign_key: :profile_id

  filter :invitation_token
end
```

**Comment by CharlieIGG** [comment]
@lgebhardt is there any way to use :underscored_key for a specific relationship key?

**Comment by tommy-russoniello** [comment]
@CharlieIGG There is not currently a way to set the formatter per relationship (except maybe with some hacking). You can however set it per controller by overriding the [private `key_formatter` instance method](https://github.com/cerebris/jsonapi-resources/blob/7a2de3076fa30312ef8d4ed76bee02156e1455d0/lib/jsonapi/acts_as_resource_controller.rb#L212-L214).
