### ISSUE TITLE
Has_one relation doesn't check for existence

### ISSUE THREAD

**Issue by 7h3kk1d** [JSONAPI-Resources/jsonapi-resources#70]
I'm not sure if I'm doing something wrong but I have a has_one relationship in one of my resources and if I create an instance using the create route and put in a links parameter. It doesn't check if the associated record exists before retrieving it.

**Comment by lgebhardt** [comment]
I was just starting to look at this. What was the resolution?

**Comment by 7h3kk1d** [comment]
I reworked something on my end so it didn't matter anymore. I didn't want to create more work if no one else was complaining.

**Comment by lgebhardt** [comment]
Ok, thanks. I'll still take a look at it then.

**Comment by lgebhardt** [comment]
Were you seeing the normal Rails behavior of not validating the existence of a related object? If so, there are a few ways you can fix that. The first is using a validation gem such as https://github.com/perfectline/validates_existence, which I have not tested. Another way would  be to put foreign key constraints on the database and handle the error when the resource is saved. And finally you could override the `verify_key` method on your `resource` (or base_resource). For example:

``` ruby
def verify_key(key, context = nil)
  #try to load a resource to make sure it exists. Will raise a JSONAPI::Exceptions::RecordNotFound if the resource is not found
  find_by_key(key, context: context)
  return key
end
```

I personally like overriding the `verify_key` method, however if you use your models outside of `jsonapi-resources` one of the other approaches might be better. I'm also a firm believer in foreign keys as an additional safety measure.

One final note, using the `verify_key` method can also provide a way to check if the current user has permission to see the related record since the context can be taken into account during the `find_by_key` method.

**Comment by 7h3kk1d** [comment]
Okay. Thanks very much! I added the database constraint.
