### ISSUE TITLE
save callbacks not fired when creating relationship

### ISSUE THREAD

**Issue by alyssais** [JSONAPI-Resources/jsonapi-resources#727]
If I have `Contact` and `PhoneNumber` models, like those [in the README](https://github.com/cerebris/jsonapi-resources/blob/0338317ff2aba9a4a126461e15314bb86c1cfaf2/README.md#routing), when I do

``` http
POST /contacts/1/relationships/phone-numbers HTTP/1.1
Content-Type: application/vnd.api+json

{ "data": [{ "id": "2", "type": "phone-numbers" }] }
```

the effect is basically `PhoneNumber.find(2).update(contact_id: 1)`.

Since this updates the `PhoneNumber`, I'd expect it to fire the `before_save` callback on the `PhoneNumberResource` before it does so. However, because of the way [this is implemented](https://github.com/cerebris/jsonapi-resources/blob/4015be1dc3f74e646d5b814c4c25793666ee2baa/lib/jsonapi/resource.rb#L228) (concatenating to the relationship, like `Contact.find(1).phone_numbers << PhoneNumber.find(2)`), the `PhoneNumber`'s, `contact_id` attribute would only be updated when the change is saved (so no chance to intercept it beforehand).

To fix this, it could reflect on the associated to find the foreign key, set the `contact_id` on the `PhoneNumber`, run the `before_save` callback, then save the `PhoneNumber`.

What do you think?

**Comment by lgebhardt** [comment]
The situation becomes less clear when you have a "has many through" relationship. While there is a model for the relationship table, there may not be a resource for it. For example we may have a system where a phone_number can be assigned to multiple contacts through a contact_phone_numbers linking table. This could have a resource or not, it doesn't really matter for this example. If you make the same request in when a linking table is used neither the Contact or the Phone Number resources will be "saved" so that creates a bit of a problem.

I'm not sure what the right answer is. I'm open to suggestions.

**Comment by alyssais** [comment]
The way I would expect this to work as a user is that I would create a ContactPhoneNumberResource class that had the `before_save` in it (and pretty much nothing else).

**Comment by lgebhardt** [comment]
I added #739 to handle this. It does not attempt to handle the "has many through" case where the intermediate table is also a resource. Those should be handled as two separate has_many relationships and you can access the related relationship through the intermediate resource.

@penman Let me know if this addresses your needs.

**Comment by alyssais** [comment]
Great, thanks @lgebhardt. I'll have a look soon.

**Comment by alyssais** [comment]
Works perfectly! Thanks @lgebhardt!
