### ISSUE TITLE
Nested abstract resources with relationships cause warning

### ISSUE THREAD

**Issue by satoko-a** [JSONAPI-Resources/jsonapi-resources#753]
With these resources, I can't avoid a warning message.

``` ruby
class GrandAbstractResource < JSONAPI::Resource
  abstract
  has_one :order
end

class AbstractResource < GrandAbstractResource
  abstract
end

class UserResource < AbstractResource
end

class OrderResource < JSONAPI::Resource
end
```

Then starts my server...

``` bash
$ bin/rails s
...
[MODEL NOT FOUND] Model could not be found for AbstractResource. If this a base Resource declare it as abstract.
...
```

As you see, `AbstractResource` is declared as abstract.
How can I avoid this warning?

You can see the whole project at [satoko-a/jr-sample](https://github.com/satoko-a/jr-sample).

**Comment by lgebhardt** [comment]
It's happening because we are rebuilding the relationships from the base class in the `inherited` method.  https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/resource.rb#L332

At that point in the code it hasn't evaluated the `abstract` method for the derived class. I don't have a fix at this point, just this explanation.

**Comment by satoko-a** [comment]
OK, thanks for your reply!

**Comment by kishorekanduluru** [comment]
is there any solution for this ?
`class CourseResource < JSONAPI::Resource`
`end`

`class ArticleResource < CourseResource`
  `model_name 'Course'`
`end`


Model could not be found for ArticleResource. If this a base Resource declare it as abstract

**Comment by lgebhardt** [comment]
@kishorekanduluru PR #955 was recently merged to master which should fix this issue, or at the least clarify the behavior.
