### ISSUE TITLE
:id must be in the updateable_fields for RC2?

### ISSUE THREAD

**Issue by barelyknown** [JSONAPI-Resources/jsonapi-resources#78]
I'm working on converting an application over to the `jsonapi_rc2` branch. I just noticed that a resource must have `:id` in its `updateable_fields` or else it receives a `Param not allowed` error (because `:id` is not in the `formatted_allowed_fields`). But, if you leave `:id` out of the `data`, you receive an "A key is required" error.

What is the intended behavior? I'm working on this today and can implement any changes that are required.

**Comment by lgebhardt** [comment]
That behavior was not intended.  Since `type` and `id` are required fields in the spec I'd like to remove them from being processed by the `updateable_fields` and `createable_fields` functions. In other words the resource shouldn't be able to override the spec. I added a hack where I insert the `id` field in the `inherited` method. This was done to allow a formatter to be set for the `id`, but I've planning on revisiting this.

**Comment by barelyknown** [comment]
Closed by https://github.com/cerebris/jsonapi-resources/pull/79.

**Comment by arcreative** [comment]
So what was the conclusion on this?  I've tried updating to the 0.7.1.beta1 and I can't either include the ID on the payload nor omit it for the reasons @barelyknown mentions.  Little confused, little help?
