### ISSUE TITLE
Performance Degradation Going From 0.7.1 to 0.8.0

### ISSUE THREAD

**Issue by travisofthenorth** [JSONAPI-Resources/jsonapi-resources#854]
My team and I upgraded from `0.7.1.beta2` to `0.8.0` and saw a pretty significant negative impact on performance, i.e. our request queueing/response times jumped up ~30ms. For our purposes, that 30ms is a deal-breaker so we were forced to revert.

Are there any guesses as to what code in `0.8.0` might have introduced the performance regression? I would be happy to help identify/fix any issues, and IMO they should be addressed now before the performance problem compounds any further. We are unfortunately pinned to `0.7.1.beta2` and I would love to unblock the upgrade.

**Comment by lgebhardt** [comment]
That sounds bad. Can you give me a few more details on what the before and after times were? 10ms to 40ms or 300ms to 330ms makes a big difference 😄, though both are obviously bad. Did you change anything else at the same time such as the version of rails?

What type of requests are seeing this jump? Size of the dataset being returned? Percent of time in the db code? Anything else you can think of that might be relevant?

You could also try the master branch. This has caching added so it might mitigate some of the time lost, but I'd like to figure out the cause since it's likely still slowing the master branch down.

**Comment by travisofthenorth** [comment]
@lgebhardt we went from ~60ms to ~90ms average response time. The PR that was deployed contained only the gem upgrade and nothing else.

The service is very young, so there's only a single endpoint being used in production. It's a `PUT` request...a custom action, so we have our own controller code. It tends to spend about 50% of the time in postgres (35ms), and that number remained consistent after the upgrade. The response body is a list of `JSONAPI::Resource` objects (3-6 of them). The resource only has 5 attributes, 2 of which are queried from a related model.

Does this help? Let me know if you need any other info.

**Comment by lgebhardt** [comment]
@travisofthenorth I'm not seeing much that should cause that large of a slowdown. Would it possible for you to do a few timings with different parts of your app to help isolate whether it's in the update code or the serialization of the response data?

If I had to guess the main areas that could be slower are serialization now loads the related models to get the id in the case that it can't be determined from the relationship. And resources can now use relationship reflection to ensure callbacks are fired on the related resources as well. However I'm assuming you did not turn on the new relationship reflection option? It is definitely slower, but is off by default because of it. And it's always possible I'm missing something big.

**Comment by travisofthenorth** [comment]
@lgebhardt I did some testing in a vacuum (i.e. one thread making requests one-at-a-time, one web server thread) and A/B testing 0.7.1 and 0.8.0. When I tested like this, it actually turns out that 0.8.0 is _faster_. I don't know if there was some kind of blackhole anomaly with our blue/green deploys when we previously attempted the upgrade, but these results seem to suggest that the performance does not get worse in the latest version. FYI, the resources in question are very lightweight (they do not load associations, no callbacks, etc.).

We are going to attempt the upgrade again with a little more care and I will update this thread after we do so.

**Comment by travisofthenorth** [comment]
@lgebhardt sorry, forgot to circle back on this. It turns out that we are having no issues with 0.8.0. I'm sorry for the misinformation! We must have had some kind of auto-scaling issue that didn't recover gracefully, and we rolled back prematurely. We are running 0.8.0 and have totally smooth performance. I will close the issue.
