### ISSUE TITLE
Seializer generates incorrect links when using inside an engine

### ISSUE THREAD

**Issue by AMHOL** [JSONAPI-Resources/jsonapi-resources#90]
When using JR in an engine, the resource serializer generates invalid URI's as it assumes a resourceful path and infers from the module nesting, however, an engine itself is namespaced and this namespace is included in the generated URI, i.e. for an API engine:

``` ruby
Rails.application.routes.draw do
  mount Api::Engine, at: 'api'
end

Api::Engine.routes.draw do
  namespace :v1 do
    resources :users
  end
end
module Api
  module V1
    class UsersController < ApplicationController
    end
  end
end
module Api
  module V1
    class UserResource < JSONAPI::Resource
      model_name 'Api::User'

      attribute :email
    end
  end
end
```

Generates:

``` json
{
  "data": [
    {
      "id": null,
      "email": "test@test.com",
      "type": "users",
      "links": {
        "self": "http://localhost:3000/api/v1/users/"
      }
    }
  ]
}
```

**Comment by AMHOL** [comment]
I know that I used `resources` here rather than `jsonapi_resources`, but after patching `resource_for` as described in #91 and changing the route to use `jsonapi_resources`  the error still applies

**Comment by lgebhardt** [comment]
Sorry to take so long to look at this (vacation and then catching up to do). I'm a bit confused by the engine being named `api` and the resources also being under and `api` module. Are you saying the link should be `http://localhost:3000/api/api/v1/users/`?

**Comment by AMHOL** [comment]
Sorry I edited the namespace, the link you posted is actually what it generates, whereas the one I posted is the one I would expect

**Comment by lgebhardt** [comment]
`http://localhost:3000/api/api/v1/users/` is the result I would expect, though I haven't tried the code in an engine. So to me it seems to be working correctly. My understanding of engines is limited, but I thought they were supposed to host the app as normal under the specified path. Correct me if I'm wrong.

If that's the case you could simply remove the `Api` level module and start with the version, which would give you the path you want.

**Comment by AMHOL** [comment]
The rails engine generator generates a namespace with the same name as the engine, and you call isolate namespace to stop anything from leaking into your application code. There will be other cases where people don't want a direct mapping from namespaced class to URI so I think it would be better if it were configurable?

**Comment by fotinakis** [comment]
I've just hit this also but I'm not using a Rails Engine—I just namespace my resource classes inside modules, like this:

``` Ruby
module MyProject
  class UserResource < JSONAPI::Resource
  end
end
```

But that produces self links that are "incorrect" for me:

``` Ruby
user_resource = MyProject::UserResource.new(user)
JSONAPI::ResourceSerializer.new(MyProject::UserResource).serialize_to_hash(user_resource)
...
"links" => {"self"=>"/myproject/users/417"},
```

When what I want is `/users/417`. I've tried to build a [custom route formatter](https://github.com/cerebris/jsonapi-resources/blob/a263bdde288086d5965a146cbe082b16b1d4ae60/lib/jsonapi/formatter.rb#L105) which simply returns a blank string for the module route, but that results in links like `"links" => {"self"=>"///416"},` I think because of how [formatted_module_path](https://github.com/cerebris/jsonapi-resources/blob/2ed04988eea53d9d348d53f6a20b519c4f0d68c7/lib/jsonapi/resource_serializer.rb#L223) works.

Would appreciate any guidance on the right way to do this, I'm newly adopting JSON:API and just hit this.

**Comment by fotinakis** [comment]
I decided to just use a `V1::` module namespace so that the defaults work correctly for me, but I agree this is a bigger issue for people using Rails Engines to isolate their API code (or anyone whose module structure doesn't map directly to their URLs).

:+1: to making this a bit clearer/easier for that case—if a custom RouteFormatter is the right way to solve it, maybe just some documentation on how to do that would be enough?

**Comment by thibaudgg** [comment]
I have the same issue, using header based versioning (with versionist gem) and api subdomain. 
My routes:

``` ruby
  constraints subdomain: 'api' do
    namespace :api, path: '' do
      api_version( module: 'V1',
          header: {
            name:  'Accept',
            value: 'application/vnd.api+json; company.api.version=1'
          }
      ) do
        jsonapi_resources :users
      end
    end
  end
```

I need to have my links like `api.company.com/users/1` and not `api.company.com/api/v1/users/1`.

**Comment by adomokos** [comment]
I got around the challenge @thibaudgg describes above with this custom RouteFormatter:

```
class RemoveAPIFromResourceRoutesFormatter < JSONAPI::RouteFormatter
  class << self
    def format(route)
      route.slice!("API::")
      super
    end
  end
end

JSONAPI.configure do |config|
  config.route_format = :remove_api_from_resource_routes
end
```

Sadly, this does not work any more with version 0.5.2. :cry: Is there a way to exclude the word "api" from the generated link when I use the subdomain `api`?

**Comment by thibaudgg** [comment]
@adomokos did you give a try to https://github.com/cerebris/jsonapi-resources/issues/257#issuecomment-122228952?
