### ISSUE TITLE
Could I query records with resource class?

### ISSUE THREAD

**Issue by zfben** [JSONAPI-Resources/jsonapi-resources#907]
For example:

```ruby
PageResource.filter(title: 'abc').data #=> {data: [{id...}]}
```

I love resource's dsl, and want to query them in rails project, not only with http request.

**Comment by lgebhardt** [comment]
Sure, use the `find_records` or `filter_records` method on your resource. Both will return an `ActiveRecord::Relation` which you can then use to get the records. The methods expect filters to be already parsed and validated. `find_records` calls `filter_records` and also applies pagination and sorting if specified, though since both return an `ActiveRecord::Relation` you can make further refinements to afterwards.

```ruby
PageResource.filter_records(title: 'abc').to_a
```

**Comment by zfben** [comment]
Thank you, it's useful 👍

**Comment by zfben** [comment]
@lgebhardt could i pass page params to query?

**Comment by lgebhardt** [comment]
`find_records` will handle pagination but you will need to specify an option for both `paginator` and `sort_criteria`.

**Comment by zfben** [comment]
thank you 👍
