### ISSUE TITLE
wrong query 

### ISSUE THREAD

**Issue by appunnicer13** [JSONAPI-Resources/jsonapi-resources#920]
Processing by UsersController#show as JSON
  User Load (1.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` IS NULL ORDER BY `users`.`id` ASC LIMIT 1

wrong query is being  issued  for http://localhost:3000/users.json , any idea why this would happen  ? 

Using rails 5 
with mysql2
output : 
{
  "errors": [
    {
      "title": "Record not found",
      "detail": "The record identified by  could not be found.",
      "code": "404",
      "status": "404"
    }
  ]
}

but i have 50 users in my db

**Comment by lgebhardt** [comment]
As you have the url I'd expect it to be routing to the `index` method. For some reason it's going to show and the id is null, hence the SQL where condition looking trying to find users with a null id. Something seems wrong with your routes.

For a show you should need to specify the user id, such as `http://localhost:3000/users/1`. Also you don't need the `.json` at the end, but I don't think it should hurt.

What do your routes and controller look like?

**Comment by appunnicer13** [comment]
empty , I included json api in application_controller , i have all the necessary controllers and models and resources and jsonapi_resources instead of resource in the routes

**Comment by lgebhardt** [comment]
Which version of JR?

**Comment by appunnicer13** [comment]
master

**Comment by appunnicer13** [comment]
class PostsController < ApplicationController
  def index
    @posts = Post.all
    render json: @posts
  end

  def show
    @post = Post.where(:id => params[:id]).first
    render json: @post
  end
end

I am trying active model serializers
And its still giving the same problem 
So i guess its  some mistake from my part 
I am new to Rails

**Comment by lgebhardt** [comment]
For JR try

```ruby
class PostsController < ApplicationController
  include JSONAPI::ActsAsResourceController
end
```

with nothing else and for routes:

```ruby
Rails.application.routes.draw do
  jsonapi_resources :posts
end
```

**Comment by appunnicer13** [comment]
i did

**Comment by lgebhardt** [comment]
That's working for me with the master branch. If you do:

```bash
rake routes
```

what do you get?

**Comment by Joseph94m** [comment]
Hey, I am sort of having the same error. When I call /api/v1/public/xxx-os, I expect an index request but I get an error 500 with the following message:


`"{\"errors\":[{\"title\":\"Internal Server Error\",\"detail\":\"Internal Server Error\",\"code\":\"500\",\"status\":\"500\",\"meta\":{\"exception\":\"No route matches {:action=\\u003e\\\"show\\\", :controller=\\u003e\\\"api/v1/public/xxx_os\\\", :id=\\u003e\\\"\\\"}, missing required keys: [:id]\"`

Doing a post with the same route /api/v1/public/xxx-os works perfectly fine, so does doing a member get request :/api/v1/public/xxx-os/id.

My rake route returns:
```
GET    /api/v1/public/xxx-os(.:format)                      api/v1/public/xxx_os#index
POST   /api/v1/public/xxx-os(.:format)                      api/v1/public/xxx_os#create
GET    /api/v1/public/xxx-os/:id(.:format)                  api/v1/public/xxx_os#show
PATCH  /api/v1/public/xxx-os/:id(.:format)                  api/v1/public/xxx_os#update
PUT    /api/v1/public/xxx-os/:id(.:format)                  api/v1/public/xxx_os#update
DELETE /api/v1/public/xxx-os/:id(.:format)                  api/v1/public/xxx_os#destroy
```

I am not sure why that would happen!

The controllers are empty and namespaced correctly. 

 ```

Rails.application.routes.draw do
namespace :api do
    namespace :v1 do
      namespace :public do
        jsonapi_resources :xxx_os do
          jsonapi_related_resources :types
        end

        namespace 'xxx_os', path: 'xxx-os' do
          jsonapi_resources :types do
          end
        end
end
end
end
```

my inflection file:

ActiveSupport::Inflector.inflections do |inflect|
  inflect.uncountable %w[xxx_os]
end



I have removed the other resources.

**Comment by lgebhardt** [comment]
It looks like the system is interpreting your request as a `show` instead of an `index` and the `show` requires an id.

I wonder if it's related to your inflections. Do other resources work with a similar request? How are you making the request? In https://github.com/cerebris/peeps I have a few curl examples that I know work if you want an example. From the peeps demo app the routes look like:

```
                             Prefix Verb      URI Pattern                                                                              Controller#Action

                           contacts GET       /contacts(.:format)                                                                      contacts#index
                                    POST      /contacts(.:format)                                                                      contacts#create
                            contact GET       /contacts/:id(.:format)                                                                  contacts#show
                                    PATCH     /contacts/:id(.:format)                                                                  contacts#update
                                    PUT       /contacts/:id(.:format)                                                                  contacts#update
                                    DELETE    /contacts/:id(.:format)                                                                  contacts#destroy
```

Note the prefix column. What do your prefixes look like?

**Comment by Joseph94m** [comment]
By the way, the errors i am getting are after I upgraded from 0.9.6 to 0.9.7 if that helps.

All of my other resources work with all of the requests (I have about 20 resources and each has 5 requests, so about 100 working requests!) . Though this is the only resource with an inflection because it ends with an 's', and as you know, by default jsonapi interprets the 's' as a demarcation of plurality causing problems when fetching the appropriate resource and controller files.
Currently I am making the requests through spec files. An example of such a request would be:

``` 
Causes an error:

route '/api/v1/public/xxx-os', 'XXX Collection' do
    get 'Get XXX-Os' do
      example 'List XXX-os.' do
        do_request
        expect(status).to eq(200)
      end
    end
  end
```


```
Does not cause an error
route '/api/v1/public/xxx-os', 'XXX Collection' do
    post 'Get XXX-Os' do
    let(:raw_post) { @payload.to_json }
      example 'List XXX-os.' do
        do_request
        expect(status).to eq(201)
      end
    end
  end
```

```
Does not cause an error
  route '/api/v1/public/xxx-os/:id', 'XXX-Os Member' do
    parameter :id, type: :string, required: true
    let(:id) { '1' }
    get 'Get XXX-os' do
      example 'Show XXX-os by id.' do
        do_request
        expect(status).to eq(200)
      end
    end
end
```



For example, i have the following resource called app (apps) which has exactly the same function as xxx_os (but we seperate them for business reasons):

```
Rails.application.routes.draw do
namespace :api do
   namespace :v1 do
     namespace :public do
       jsonapi_resources :xxx_os do
         jsonapi_related_resources :types
       end

       namespace 'xxx_os', path: 'xxx-os' do
         jsonapi_resources :types do
         end
       end
       jsonapi_resources :apps do
         jsonapi_related_resources :types
       end

       namespace :apps do
           jsonapi_resources :types do
           end
       end
    end
  end
end
```




You're right about the prefix thing. For some reason my index and post for xxx_os require an index. That is odd especially considering that the post request works without providing an index!.

   ```
api_v1_public_xxx_os_index GET    /api/v1/public/xxx-os(.:format)              api/v1/public/xxx_os#index
                               POST   /api/v1/public/xxx-os(.:format)              api/v1/public/xxx_os#create
         api_v1_public_xxx_os GET    /api/v1/public/xxx-os/:id(.:format)          api/v1/public/xxx_os#show
                               PATCH  /api/v1/public/xxx-os/:id(.:format)          api/v1/public/xxx_os#update
                               PUT    /api/v1/public/xxx-os/:id(.:format)          api/v1/public/xxx_os#update
                               DELETE /api/v1/public/xxx-os/:id(.:format)          api/v1/public/xxx_os#destroy
```


The apps one looks something like that:

```
         api_v1_public_apps GET    /api/v1/public/apps(.:format)                  api/v1/public/apps#index
                            POST   /api/v1/public/apps(.:format)                  api/v1/public/apps#create
          api_v1_public_app GET    /api/v1/public/apps/:id(.:format)              api/v1/public/apps#show
                            PATCH  /api/v1/public/apps/:id(.:format)              api/v1/public/apps#update
                            PUT    /api/v1/public/apps/:id(.:format)              api/v1/public/apps#update
                            DELETE /api/v1/public/apps/:id(.:format)              api/v1/public/apps#destroy
```


Also on a side note if I keep 

`jsonapi_related_resources :types`

in

```
       jsonapi_resources :xxx_os do
         jsonapi_related_resources :types
       end
```
i get the error that:

>  Invalid route name, already in use: 'api_v1_public_xxx_os_types' 
  You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
  http://guides.rubyonrails.org/routing.html#restricting-the-routes-created

Which is odd because i do not get it for apps even though it's the same code. I think this is related to my original problem and it would probably be solved by solving the initial one. I've commented that line for now so I can solve the original problem.


Thank you for your quick response by the way!

**Comment by lgebhardt** [comment]
In 0.9.7 we switched to using the route helpers to generate links in the payload and there were a few changes in the routing functions to ensure the route helper names were consistent. #1251 reported a bug where the related function name was not always unique. This was fixed in #1252, but I haven't built a release around it yet. You could test that change with the `release-0-9` branch. That may fix the last error you reported.

I'm thinking the routes are adding the `index` to the prefix (`api_v1_public_xxx_os_index`) to disambiguate the `index` from the `show`. With that I'd expect the routing in your request to work since the routes do work. I'm not familiar with the spec format you're using, but I wonder if the issue is in there. Can you test using curl?

**Comment by Joseph94m** [comment]
`curl -i -H "Accept: application/vnd.api+json" -H "Content-Type: application/vnd.api+json" -H "Authorization: Bearer myToken" "https://hiddenhost/api/v1/public/xxx-os"
`

> HTTP/2 500 
> date: Thu, 30 May 2019 13:23:16 GMT
> content-type: application/vnd.api+json
> x-frame-options: DENY
> x-xss-protection: 1; mode=block
> x-content-type-options: nosniff
> x-download-options: noopen
> x-permitted-cross-domain-policies: none
> referrer-policy: strict-origin-when-cross-origin
> cache-control: no-cache
> x-request-id: f3977fff2d0f02633b0dc444d0fd485a
> x-runtime: 0.622126
> vary: Origin
> server: adasdasdadsa
> content-security-policy: ****hidden****
> strict-transport-security: max-age=15724800; includeSubDomains
> 
> {"errors":[{"title":"Internal Server Error","detail":"Internal Server Error","code":"500","status":"500"}]}



Detail: ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"api/v1/public/xxx_os", :id=>""}, missing required keys: [:id]

Same thing. Also tried it with Postman. Same error.

Curl on other resources does work using the same syntax but by replacing xxx-os in `"https://hiddenhost/api/v1/public/xxx-os"` by the appropriate resource.

I will try the `release-0-9` later on today and will let you know if it works for the second problem.

**Comment by Joseph94m** [comment]
> In 0.9.7 we switched to using the route helpers to generate links in the payload and there were a few changes in the routing functions to ensure the route helper names were consistent. 
> 

I guess that's why I have been receiving the following warnings while running my tests:

`self_link for Api::V1::Public::AppResource.types(ToMany) could not be generated  

self_link for Api::V1::Public::TypesResource.configs(ToMany) could not be generated`

**Comment by lgebhardt** [comment]
@Joseph94m Thanks for trying curl. I'll see if I can reproduce and fix this.

**Comment by Joseph94m** [comment]
@lgebhardt The `release-0-9` fixed the second problem I mentioned. Thank you. I await your return for my original problem.

**Comment by lgebhardt** [comment]
@Joseph94m I'm not able to reproduce the issue you're having. I created a simple change to the peeps app that works on my system with both v0.9.6 and v0.9.7. It's at https://github.com/cerebris/peeps/tree/test_inflections if you want to compare it to your changes.

**Comment by Joseph94m** [comment]
@lgebhardt , I was able to fix this issue 'forcefully'. By changing the route from:


```
        jsonapi_resources :xxx_os  do
          jsonapi_related_resources :types
        end
```

to

```
        jsonapi_resources :xxx_os , only: %i[index] do
          jsonapi_related_resources :types
        end

```

Obviously this isn't the solution I am looking for since I need the show, post and put requests, but i think this is one step closer towards the solution.

Could it be related to the addition of the route helper? I've looked through the commits of the latest version but i could not make out how to use them. When running the tests I usually get warnings (even though the tests are passing):
```
self_link for Api::V1::Public::AppResource.types(ToMany) could not be generated

self_link for Api::V1::Public::TypesResource.configs(ToMany) could not be generated
```

**Comment by lgebhardt** [comment]
@Joseph94m Could you put together a small app showing this failing? There's obviously something I'm missing in your setup.

The self_link could not be generated messages will happen if the resources are not routable. You can suppress the warnings by excluding the links if that is intentional. See http://jsonapi-resources.com/v0.9/guide/resources.html#Links

**Comment by Joseph94m** [comment]
@lgebhardt Ok. I will wait for my colleague to be back next so he can have a look at what was done so far. If we can't find a solution together we will make a small app and share it with you. Thank you.
